ScreenManager:
    id: manager
    MainScreen:
        id: mainscreen
    InformationScreen:
        id: informationscreen
    ThermodynamicsScreen:
        id: thermoscreen
    WorkingFluidInfoScreen:
        id: workingfluidinfoscreen
    HeatSourceInfoScreen:
        id: heatsourceinfoscreen
    ThermoStateScreen:
        id: thermostatescreen

<MainScreen>
    
    name: 'main'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'ORCestra'
                        left_action_items: [["menu", lambda x: nav_drawer.set_state()]]
                        elevation:5

                    ScrollView:
                        MDGridLayout:
                            id: box
                            cols: 1
                            adaptive_height: True
                        
                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1, None
                                size: dp(350), dp(350) 
                                allow_stretch: True
                                keep_ratio: True

                                MDLabel:
                                    text: "Thermodynamic Cycle"
                                    theme_text_color: "Secondary"
                                    halign: 'center'
                                    size_hint: 1,None
                                    height: dp(40)
                                    font_style: "H5"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                Image:
                                    allow_stretch: True
                                    keep_ratio: True
                                    source:"ORCFigureLayout.JPG"
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRectangleFlatIconButton:
                                    icon: "information"
                                    text: "Information"
                                    color: (0.28, 0.39, 0.63, 1)
                                    pos_hint: {"center_x":0.5,"center_y":0.5}
                                    size_hint: 0.4,None
                                    on_release:
                                        root.manager.screens[1].infovalue = 0
                                        root.manager.current = 'info'
                                        root.manager.transition.direction = "left"
                                                                            
                  
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRaisedButton:
                                    text: "Start Simulation"
                                    text_color: (1, 1, 1, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    on_release: 
                                        root.manager.current = 'thermo'
                                        root.manager.transition.direction = "left"
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height:dp(260)
                                allow_stretch: True
                                keep_ratio: True

                                MDLabel:
                                    text: "Velocity Triangles"
                                    theme_text_color: "Secondary"
                                    font_style: "H5"
                                    halign: 'center'
                                    size_hint: 1,None
                                    height: dp(40)
                                    theme_text_color: "Custom"
                                    text_color: (0.19, 0.64, 0.20, 1)

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                Image:
                                    allow_stretch: True
                                    keep_ratio: True
                                    source:"VelocityTriangles.png"

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRectangleFlatIconButton:
                                    icon: "information"
                                    text: "Information"
                                    text_color: (0.19, 0.64, 0.20, 1)
                                    icon_color: (0.19, 0.64, 0.20, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    line_color: (0.19, 0.64, 0.20, 1)
                                    on_release:
                                        root.manager.screens[1].infovalue = 1
                                        root.manager.current = 'info'
                                        root.manager.transition.direction = "left"

                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRaisedButton:
                                    text: "Start Simulation"
                                    text_color: (1, 1, 1, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    md_bg_color: (0.19, 0.64, 0.20, 1)
                                    on_release: root.manager.current = 'main'
                                        
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height:dp(453)
                                allow_stretch: True
                                keep_ratio: True

                                MDLabel:
                                    text: "Stator Design"
                                    theme_text_color: "Secondary"
                                    font_style: "H5"
                                    halign: 'center'
                                    size_hint: 1,None
                                    height: dp(40)
                                    theme_text_color: "Custom"
                                    text_color: (0.90, 0.36, 0.0, 1)

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
  
                                Image:
                                    allow_stretch: True
                                    keep_ratio: True
                                    source:"StatorBladeImage.png"

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRectangleFlatIconButton:
                                    icon: "information"
                                    text: "Information"
                                    text_color: (0.90, 0.36, 0.0, 1)
                                    icon_color: (0.90, 0.36, 0.0, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    line_color: (0.90, 0.36, 0.0, 1)
                                    on_release:
                                        root.manager.screens[1].infovalue = 2
                                        root.manager.current = 'info'
                                        root.manager.transition.direction = "left"

                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRaisedButton:
                                    text: "Start Simulation"
                                    text_color: (1, 1, 1, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    md_bg_color: (0.90, 0.36, 0.0, 1)
                                    on_release: root.manager.current = 'main'
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height:dp(340)
                                allow_stretch: True
                                keep_ratio: False

                                MDLabel:
                                    text: "Rotor Design"
                                    theme_text_color: "Secondary"
                                    font_style: "H5"
                                    halign: 'center'
                                    size_hint: 1,None
                                    height: dp(40)
                                    theme_text_color: "Custom"
                                    text_color: (0.48, 0.0, 0.80, 1)

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                Image:
                                    allow_stretch: False
                                    keep_ratio: False
                                    source:"RotorBladeImage.png"

                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRectangleFlatIconButton:
                                    icon: "information"
                                    text: "Information"
                                    text_color: (0.48, 0.0, 0.80, 1)
                                    icon_color: (0.48, 0.0, 0.80, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint: 0.4,None
                                    line_color: (0.48, 0.0, 0.80, 1)
                                    on_release:
                                        root.manager.screens[1].infovalue = 3
                                        root.manager.current = 'info'
                                        root.manager.transition.direction = "left"
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)
                                    
                                MDRaisedButton:
                                    text: "Start Simulation"
                                    text_color: (1, 1, 1, 1)
                                    pos_hint: {"x":0.3}
                                    size_hint_x: 0.4
                                    md_bg_color: (0.48, 0.0, 0.80, 1)
                                    on_release: 
                                        root.manager.current = 'main'
                                        root.manager.transition.direction = "left"
                                    
                                MDSeparator:
                                    height: dp(10)
                                    color: (1,1,1,1)

        MDNavigationDrawer:
            id: nav_drawer
            ContentNavigationDrawer:
                orientation: 'vertical'
                padding: dp(8)
                spacing: dp(8)

                MDLabel:
                    text: "ORCestra/ Main Page"
                    font_style: "H6"
                    size_hint: 1, None
                    height: dp(40)
                    pos_hint: {"x":0.05,"top":1}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                                                    
                Image:
                    id: avatar
                    size_hint: (1,None)
                    source: "ORCestra_white_1080.png"
                    height: dp(200)
                
                ScrollView:
                    DrawerList:
                        id: md_list
                        
                        MDList:
                            OneLineIconListItem:
                                text: "Home"
                                on_release: 
                                    root.manager.current = 'main'
                                    root.manager.transition.direction = 'right'

                            
                                IconLeftWidget:
                                    icon: "home"

                            OneLineIconListItem:
                                text: "Thermodynamic Cycle"
                                on_release: 
                                    nav_drawer.set_state("close")
                                    root.manager.current = 'thermo'
                                    root.manager.transition.direction = 'right'
                                theme_text_color: "Custom"
                                text_color: (0.28, 0.39, 0.63, 1)
                            
                                IconLeftWidget:
                                    icon: "alpha-t-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)

                                    
                            OneLineIconListItem:
                                text: "Velocity Triangles"
                                theme_text_color: "Custom"
                                text_color: (0.19, 0.64, 0.20, 1)
                                on_release:
                                    nav_drawer.set_state("close")
                                    root.manager.current = 'main'
                                    root.manager.transition.direction = 'right'
                            
                                IconLeftWidget:
                                    icon: "alpha-v-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.19, 0.64, 0.20, 1)


                            OneLineIconListItem:
                                text: "Stator Design"
                                on_release:
                                    nav_drawer.set_state("close")
                                    root.manager.current = 'main'
                                    root.manager.transition.direction = 'right'
                                theme_text_color: "Custom"
                                text_color: (0.90, 0.36, 0.0, 1)
                            
                                IconLeftWidget:
                                    icon: "alpha-s-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.90, 0.36, 0.0, 1)
                                    
                            OneLineIconListItem:
                                text: "Rotor Design"
                                on_release:
                                    nav_drawer.set_state("close")
                                    root.manager.current = 'main'
                                    root.manager.transition.direction = 'right'
                                theme_text_color: "Custom"
                                text_color: (0.48, 0.0, 0.80, 1)
                            
                                IconLeftWidget:
                                    icon: "alpha-r-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.48, 0.0, 0.80, 1)

                            OneLineIconListItem:
                                text: "Exit"
                                on_release: app.stop()
                            
                                IconLeftWidget:
                                    icon: "logout"
                                    
<InformationScreen>
    infotext:infotext
    infobar:infobar
    infoimage:infoimage
    infocard:infocard
    name: 'info'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        id: infobar
                        title: 'Information'
                        left_action_items: [["arrow-left-thick",  lambda x: app.change_screen('main')]]
                        elevation:5

                    ScrollView:
                        MDGridLayout:
                            id: box
                            cols: 1
                            adaptive_height: True
                            
                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height: dp(205)
                                allow_stretch: True
                                keep_ratio: False
                                    
                                Image:
                                    id: infoimage
                                    allow_stretch: True
                                    keep_ratio: True
                                    source:"ORCFigureLayout.JPG"
                                    
                            MDSeparator:
                                height: dp(10)
                                color: (1,1,1,1)
                                    
                            MDCard:
                                id: infocard
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height: dp(600)
                                allow_stretch: True
                                keep_ratio: True
                                    
                                MDLabel:
                                    id: infotext
                                    text: "Thermodynamic Cycle"
                                    size_hint: 0.95, None
                                    height: dp(900)
                                    pos_hint: {"x":0.025,"top":1}
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)

<ItemIndDialog>:
    comptext:comptext

    MDIconButton:
        icon: "alarm-panel-outline"
        pos_hint: {"x": 0.85, "center_y": .5}
        theme_text_color: "Custom"
        text_color: (0.28, 0.39, 0.63, 1)
        on_release:
            root.correct_composition(root.var)

    MDLabel:
        text: root.var
        theme_text_color: "Custom"
        text_color: 0.28, 0.39, 0.63, 1
        pos_hint: {"x":0.15,"y":0.05}

    MDTextFieldRect:
        id: comptext
        text: root.value
        hint_text: "Enter value"
        size_hint: 0.3,0.7
        pos_hint: {"x":0.55,"y":0.15}
        color_mode: 'custom'
        line_color_focus: 0.28, 0.39, 0.63, 1
        on_text:
            root.composition_check()

<ThermodynamicsScreen>:
    thermotab1:thermotab1
    thermotab2:thermotab2
    thermotab3:thermotab3
    id: thermo
    name: 'thermo'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'Thermodynamic Cycle'
                        left_action_items: [["menu", lambda x: nav_drawer_thermo.set_state("open")]]
                        elevation:5
                            
                    MDTabs:
                        allow_stretch: False
                        id: thermotabs
                        Thermotab1:
                            id: thermotab1
                            text: "Working Media"
                            thermotab2:thermotab2
                            thermotab3:thermotab3
                            
                        Thermotab2:
                            id: thermotab2
                            text: "Components"
                            thermotab1:thermotab1
                            thermotab3:thermotab3
                            
                        Thermotab3:
                            id: thermotab3
                            text: "Calculate"
                            thermotab1:thermotab1
                            thermotab2:thermotab2                    
                                
        MDNavigationDrawer:
            id: nav_drawer_thermo
            ContentNavigationDrawer:
                orientation: 'vertical'
                padding: dp(8)
                spacing: dp(8)
                
                MDLabel:
                    text: "ORCestra/ Thermodynamic Cycle"
                    font_style: "H6"
                    size_hint: 1, None
                    height: dp(40)
                    pos_hint: {"x":0.05,"top":1}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                                                    
                Image:
                    id: avatar
                    size_hint: (1,None)
                    source: "ORCFigureLayout.JPG"
                    height: dp(200)
                    
                ScrollView:
                    DrawerList:
                        id: md_list
                        
                        MDList:
                            OneLineIconListItem:
                                text: "Home"
                                on_release:
                                    nav_drawer_thermo.set_state("close")
                                    root.manager.current = 'main'

                            
                                IconLeftWidget:
                                    icon: "home"

                            OneLineIconListItem:
                                text: "Thermodynamic Cycle"
                                on_release:
                                    nav_drawer_thermo.set_state("close")
                                    root.manager.current = 'thermo'
                                theme_text_color: "Custom"
                                text_color: (0.28, 0.39, 0.63, 1)
                            
                                IconLeftWidget:
                                    icon: "alpha-t-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    
                            OneLineIconListItem:
                                text: "Velocity Triangles"
                                theme_text_color: "Custom"
                                text_color: (0.19, 0.64, 0.20, 1)
                                on_release:
                                    nav_drawer_thermo.set_state("close")
                                    root.manager.current = 'main'
                            
                                IconLeftWidget:
                                    icon: "alpha-v-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.19, 0.64, 0.20, 1)


                            OneLineIconListItem:
                                text: "Stator Design"
                                on_release:
                                    nav_drawer_thermo.set_state("close")
                                    root.manager.current = 'main'
                                theme_text_color: "Custom"
                                text_color: (0.90, 0.36, 0.0, 1)
                            
                                IconLeftWidget:
                                    icon: "alpha-s-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.90, 0.36, 0.0, 1)
                                    
                            OneLineIconListItem:
                                text: "Rotor Design"
                                theme_text_color: "Custom"
                                text_color: (0.48, 0.0, 0.80, 1)
                                on_release:
                                    nav_drawer_thermo.set_state("close")
                                    root.manager.current = 'main'
                            
                                IconLeftWidget:
                                    icon: "alpha-r-circle"
                                    theme_text_color: "Custom"
                                    text_color: (0.48, 0.0, 0.80, 1)

                            OneLineIconListItem:
                                text: "Exit"
                                on_release: app.stop()
                            
                                IconLeftWidget:
                                    icon: "logout"

<Thermotab1>:
    workingfluidbutton:workingfluidbutton
    gwp100field:gwp100field
    odpfield:odpfield
    ashrae34field:ashrae34field
    fluidtypetext:fluidtypetext
    fluidtypeimage:fluidtypeimage
    mflowtext:mflowtext
    mflowminus:mflowminus
    mflow:mflow
    mflowplus:mflowplus
    mflowreset:mflowreset
    mflowsldr:mflowsldr
    mflowround:mflowround
    massflowopt:massflowopt
    orientation: "vertical"
    cols: 1
    id: thermotab1
    ScrollView:
        do_scroll_x: True
        do_scroll_y: True
        MDGridLayout:
            id: box
            cols: 1
            adaptive_height: True
            
            MDToolbar:
                title: "Working Fluid Inputs"
                md_bg_color: (0.60, 0.76, 1, 1)
                left_action_items: [["information", lambda x: app.change_screen('workingfluidinfo')]]

            MDList:
                OneLineIconListItem:
                    id: workingfluidbutton
                    text: "Working Fluid : Select"
                    font_style: "H6"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    on_release: root.WorkingFluid_bottom_sheet()
                    
                MDGridLayout:
                    cols: 1
                    height: dp(30)
                    adaptive_height: True

                    MDCard:
                        MDLabel:
                            text:"    GWP100"
                            font_style: "H6"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.4
                            pos_hint: {"x":0.05,"center_y":0.5}

                        MDLabel:
                            text:"ODP"
                            font_style: "H6"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.3
                            pos_hint: {"x":0.4,"center_y":0.5}

                        MDLabel:
                            text:"ASHRAE34"
                            font_style: "H6"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.3
                            pos_hint: {"x":0.65,"center_y":0.5}
                            
                MDGridLayout:
                    cols: 1
                    height:dp(30)
                    adaptive_height: True

                    MDCard:
                        MDLabel:
                            id: gwp100field
                            text:"    None"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.4
                            pos_hint: {"x":0.05,"center_y":0.5}
                            
                        MDLabel:
                            id: odpfield
                            text:"None"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.3
                            pos_hint: {"x":0.4,"center_y":0.5}

                        MDLabel:
                            id:ashrae34field
                            text:"None"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x:0.3
                            pos_hint: {"x":0.75,"center_y":0.5}

                MDGridLayout:
                    cols: 1
                    height: dp(45)
                    adaptive_height: True
                    
                    MDCard:
                        MDLabel:
                            id: mflowtext
                            text: "   Mass flow [kg/s]:"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : 0.45
                            pos_hint: {"center_x":0.25,"center_y":0.5}

                        MDIconButton:
                            id: mflowminus
                            icon: "minus"
                            pos_hint: {"x": 0.55, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.mflow.text = "{:.2f}" .format(float(root.mflow.text) - 0.2)
                                root.mflowsldr.value = float(root.mflowsldr.value) - 0.2

                        MDTextFieldRect:
                            id: mflow
                            text: "2.0"
                            hint_text: "Enter value"
                            size_hint: 0.25,0.7
                            pos_hint: {"x":0.65,"center_y":0.5}
                            color_mode: 'custom'
                            multiline: False
                            line_color_focus: (0.28, 0.39, 0.63, 1)

                        MDIconButton:
                            id: mflowplus
                            icon: "plus"
                            pos_hint: {"x": 0.85, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.mflow.text = "{:.2f}".format(float(root.mflow.text) + 0.2)
                                root.mflowsldr.value = float(root.mflowsldr.value) + 0.2
                MDGridLayout:
                    cols: 1
                    height: dp(40)
                    adaptive_height: True

                    MDCard:

                        MDIconButton:
                            id: mflowreset
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            size_hint_x : None
                            icon: "restore"
                            on_release:
                                root.mflow.text = "{:.2f}".format(2.0)
                                root.mflowsldr.value = 2.0

                        MDSlider:
                            id: mflowsldr
                            min: 0.1
                            max: 10
                            value: 2
                            size_hint_x : 0.7
                            pos_hint: {"x":0.10}
                            hint: False
                            thumb_color_down: (0.28, 0.39, 0.63, 1)
                            on_value:
                                root.mflow.text = "{:.2f}".format(mflowsldr.value)

                        MDIconButton:
                            id: mflowround
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : None
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            icon: "alpha-r-circle-outline"
                            on_release:
                                root.mflow.text = "{:.2f}".format(round(float(root.mflow.text), 1))
                                root.mflowsldr.value = round(float(root.mflowsldr.value), 1)

                MDGridLayout:
                    cols: 1
                    height: dp(40)
                    adaptive_height: True

                    MDCard:
                        MDLabel:
                            text: "     Mass flow Optimazation:"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : 0.55
                            pos_hint: {"x":0.15,"y":0.05}

                        MDSwitch:
                            id: massflowopt
                            size_hint_x: 0.15
                            pos_hint: {"x":0.5,"y":0.05}
                            on_active:
                                root.OptActivate()
                            on_release:
                                root.OptActivate()
                                
                        MDLabel:
                            text: " "
                            theme_text_color: "Custom"
                            size_hint_x : 0.1

                OneLineIconListItem:
                    id: fluidtypetext
                    text: "Fluid Type : None"
                    font_style: "H6"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            MDCard:
                orientation: "vertical"
                size_hint: 1,None
                height: dp(450)
                allow_stretch: True
                keep_ratio: True

                Image:
                    id: fluidtypeimage
                    allow_stretch: True
                    keep_ratio: True
                    source:"Ts_Dry.png"


<Thermotab2>:
    heatsourcebutton:heatsourcebutton
    th1:th1
    th1sldr:th1sldr
    ph1:ph1
    ph1sldr:ph1sldr
    mhflow:mhflow
    mhflowsldr:mhflowsldr
    th2:th2
    ph2:ph2
    pinchevap:pinchevap
    pinchevapsldr:pinchevapsldr
    dosh:dosh
    doshsldr:doshsldr
    pinchcond:pinchcond
    pinchcondsldr:pinchcondsldr
    dosc:dosc
    doscsldr:doscsldr
    tw1:tw1
    tw1sldr:tw1sldr
    pw1:pw1
    tw2:tw2
    pw2:pw2
    pw1sldr:pw1sldr
    t1:t1
    p1:p1
    t2:t2
    p2:p2
    t21:t21
    p21:p21
    t3:t3
    p3:p3
    t4:t4
    p4:p4
    pinchevap:pinchevap
    dosh:dosh
    pinchcond:pinchcond
    dosc:dosc

    mwflow:mwflow
    mwflowsldr:mwflowsldr
    npump:npump
    npumpsldr:npumpsldr

    orientation: "vertical"
    cols: 1
    id: thermotab2
    ScrollView:
        do_scroll_x: True
        do_scroll_y: True
        MDGridLayout:
            id: box
            cols: 1
            adaptive_height: True
            MDToolbar:
                title: "Heat Source & Evaporator"
                md_bg_color: (0.60, 0.76, 1, 1)
                left_action_items: [["information", lambda x: app.change_screen('heatsourceinfo')]]

            MDList:
                OneLineIconListItem:
                    id: heatsourcebutton
                    text: "Heat Source : Select"
                    font_style: "H6"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"center_x":0.5, "center_y":0.5}
                    on_release: root.HeatSource_bottom_sheet()

                MDGridLayout:
                    cols: 1
                    height: dp(25)
                    adaptive_height: True
                
                    MDCard:
                        MDLabel:
                            text: "   Hot fluid Inputs:"
                            font_style: "Button"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            pos_hint: {"x":0.10,"y":0.0}

                MDGridLayout:
                    cols: 1
                    height: dp(45)
                    adaptive_height: True
                    
                    MDCard:

                        MDLabel:
                            text: "   Inlet Temperature [C]:"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : 0.45
                            pos_hint: {"center_x":0.25,"center_y":0.5}
                            
                        MDIconButton:
                            icon: "minus"
                            pos_hint: {"x": 0.55, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.th1.text = "{:.2f}".format(float(root.th1.text) - 5)
                                root.th1sldr.value = float(root.th1sldr.value) - 5

                        MDTextFieldRect:
                            id: th1
                            text: "150.0"
                            hint_text: "Enter value"
                            size_hint: 0.25,0.7
                            pos_hint: {"x":0.65,"center_y":0.5}
                            color_mode: 'custom'
                            multiline: False
                            line_color_focus: (0.28, 0.39, 0.63, 1)

                        MDIconButton:
                            icon: "plus"
                            pos_hint: {"x": 0.85, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.th1.text = "{:.2f}".format(float(root.th1.text) + 5)
                                root.th1sldr.value = float(root.th1sldr.value) + 5

                MDGridLayout:
                    cols: 1
                    height: dp(40)
                    adaptive_height: True

                    MDCard:
                        
                        MDIconButton:
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : None
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            icon: "restore"
                            on_release:
                                root.th1.text = "{:.2f}".format(150)
                                root.th1sldr.value = 150
                                
                        MDSlider:
                            id: th1sldr
                            min: 60
                            max: 450
                            value: 150
                            size_hint_x : 0.7
                            pos_hint: {"x":0.10}
                            hint: False
                            thumb_color_down: (0.28, 0.39, 0.63, 1)
                            on_value:
                                root.th1.text = "{:.2f}".format(th1sldr.value)

                        MDIconButton:
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : None
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            icon: "alpha-r-circle-outline"
                            on_release:
                                root.th1.text = "{:.2f}".format(round(float(root.th1.text)))
                                root.th1sldr.value = round(float(root.th1sldr.value))

                MDGridLayout:
                    cols: 1
                    height: dp(45)
                    adaptive_height: True
                    
                    MDCard:
                        id: itemhotinletpres

                        MDLabel:
                            text: "   Inlet Pressure [bar]:"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : 0.45
                            pos_hint: {"x":0.15,"y":0.05}
                        
                        MDIconButton:
                            icon: "minus"
                            pos_hint: {"x": 0.55, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.ph1.text = "{:.2f}".format(float(root.ph1.text) - 0.2)
                                root.ph1sldr.value = float(root.ph1sldr.value) - 0.2

                        MDTextFieldRect:
                            id: ph1
                            text: "0.989"
                            hint_text: "Enter value"
                            size_hint: 0.25,0.7
                            pos_hint: {"x":0.70,"y":0.15}
                            color_mode: 'custom'
                            multiline: False
                            line_color_focus: (0.28, 0.39, 0.63, 1)
                        
                        MDIconButton:
                            icon: "plus"
                            pos_hint: {"x": 0.85, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.ph1.text = "{:.2f}".format(float(root.ph1.text) + 0.2)
                                root.ph1sldr.value = float(root.ph1sldr.value) + 0.2
                MDGridLayout:
                    cols: 1
                    height: dp(40)
                    adaptive_height: True

                    MDCard:
                        
                        MDIconButton:
                            theme_text_color: "Custom"
                            size_hint_x : None
                            text_color: (0.28, 0.39, 0.63, 1)
                            icon: "restore"
                            on_release:
                                root.ph1.text = "{:.3f}".format(0.989)
                                root.ph1sldr.value = 0.989

                        MDSlider:
                            id: ph1sldr
                            min: 0.5
                            max: 3.5
                            value: 0.989
                            size_hint_x : 0.7
                            pos_hint: {"x":0.10}
                            hint: False
                            thumb_color_down: (0.28, 0.39, 0.63, 1)
                            on_value:
                                root.ph1.text = "{:.3f}".format(ph1sldr.value)
                                
                        MDIconButton:
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : None
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            icon: "alpha-r-circle-outline"
                            on_release:
                                root.ph1.text = "{:.2f}".format(round(float(root.ph1.text),1))
                                root.ph1sldr.value = round(float(root.ph1sldr.value),1)
                MDGridLayout:
                    cols: 1
                    height: dp(45)
                    adaptive_height: True
                    
                    MDCard:
                        id: itemhotmflow

                        MDLabel:
                            text: "   Mass Flow [kg/s]:"
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : 0.45
                            pos_hint: {"x":0.15,"y":0.05}
                            
                        MDIconButton:
                            icon: "minus"
                            pos_hint: {"x": 0.55, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.mhflow.text = "{:.2f}".format(float(root.mhflow.text) - 0.5)
                                root.mhflowsldr.value = float(root.mhflowsldr.value) - 0.5

                        MDTextFieldRect:
                            id: mhflow
                            text: "19.2"
                            hint_text: "Enter value"
                            size_hint: 0.25,0.7
                            pos_hint: {"x":0.70,"y":0.15}
                            color_mode: 'custom'
                            multiline: False
                            line_color_focus: (0.28, 0.39, 0.63, 1)

                        MDIconButton:
                            icon: "plus"
                            pos_hint: {"x": 0.85, "center_y": .5}
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            on_release:
                                root.mhflow.text = "{:.2f}".format(float(root.mhflow.text) + 0.5)
                                root.mhflowsldr.value = float(root.mhflowsldr.value) + 0.5
                        
                MDGridLayout:
                    cols: 1
                    height: dp(40)
                    adaptive_height: True

                    MDCard:
                        MDIconButton:
                            size_hint: None,None
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            icon: "restore"
                            on_release:
                                root.mhflow.text = "{:.2f}".format(19.2)
                                root.mhflowsldr.value = 19.2

                        MDSlider:
                            id: mhflowsldr
                            min: 1
                            max: 35
                            value: 19.2
                            size_hint_x : 0.7
                            pos_hint: {"x":0.10}
                            hint: False
                            thumb_color_down: (0.28, 0.39, 0.63, 1)
                            on_value:
                                root.mhflow.text = "{:.2f}".format(mhflowsldr.value)
                                
                        MDIconButton:
                            theme_text_color: "Custom"
                            text_color: (0.28, 0.39, 0.63, 1)
                            size_hint_x : None
                            pos_hint: {"center_x": 0.5, "center_y": .5}
                            icon: "alpha-r-circle-outline"
                            on_release:
                                root.mhflow.text = "{:.2f}".format(round(float(root.mhflow.text),1))
                                root.mhflowsldr.value = round(float(root.mhflowsldr.value),1)
                OneLineIconListItem:
                    height: dp(120)
                    MDLabel:
                        text: "Hot fluid Outputs:"
                        font_style: "Button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        pos_hint: {"x":0.10,"y":0.4}

                    MDLabel:
                        text: "Outlet Temperature [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.5
                        pos_hint: {"x":0.15,"y":0.10}

                    MDLabel:
                        id: th2
                        text: "None"
                        hint_text: "Enter value"
                        size_hint: 0.25,0.25
                        pos_hint: {"x":0.65,"y":0.475}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)

                    MDLabel:
                        text: "Outlet Pressure [bar]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.5
                        pos_hint: {"x":0.15,"y":-0.25}

                    MDLabel:
                        id: ph2
                        text: "None"
                        size_hint: 0.25,0.25
                        pos_hint: {"x":0.65,"y":0.125}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: Window.width*0.316239316
                allow_stretch: True
                keep_ratio: False

                Image:
                    allow_stretch: True
                    keep_ratio: False
                    source:"Evaporator.png"
            MDGridLayout:
                cols: 1
                height: dp(25)
                adaptive_height: True

                MDCard:
                
                    MDLabel:
                        text: "   Evaporator:"
                        font_style: "Button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        pos_hint: {"x":0.10,"y":0.1}
                    
            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itempinchpoint
                    MDIconButton:
                        id: infopinchevap
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "information"
                        on_release: root.show_evap_custom_bottom_sheet("pinchpoint")

                    MDLabel:
                        text: "Pinch point [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.35
                        pos_hint: {"x":0.25,"y":0.05}
                        
                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pinchevap.text = "{:.2f}".format(float(root.pinchevap.text) - 1)
                            root.pinchevapsldr.value = float(root.pinchevapsldr.value) - 1

                    MDTextFieldRect:
                        id: pinchevap
                        text: "5.00"
                        hint_text: "Enter value"
                        size_hint: 0.2,0.7
                        pos_hint: {"x":0.70,"y":0.15}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)
                        
                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pinchevap.text = "{:.2f}".format(float(root.pinchevap.text) + 1)
                            root.pinchevapsldr.value = float(root.pinchevapsldr.value) + 1

            MDGridLayout:
                cols: 1
                adaptive_height: True
                height: dp(40)

                MDCard:
                    MDIconButton:
                        id: resetpinchevap
                        size_hint_x: None
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.pinchevap.text = "{:.2f}".format(5)
                            root.pinchevapsldr.value = 5

                    MDSlider:
                        id: pinchevapsldr
                        min: 0.1
                        max: 450
                        value: 5
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.pinchevap.text = "{:.2f}".format(pinchevapsldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.pinchevap.text = "{:.2f}".format(round(float(root.pinchevap.text),0))
                            root.pinchevapsldr.value = round(float(root.pinchevapsldr.value),0)
            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itemdosh
                    MDIconButton:
                        id: infopinchevap
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "information"
                        on_release: root.show_evap_custom_bottom_sheet("dosh")

                    MDLabel:
                        text: "Degrees of superheat [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.35
                        pos_hint: {"x":0.25,"y":0.05}
                        
                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.dosh.text = "{:.2f}".format(float(root.dosh.text) - 1)
                            root.doshsldr.value = float(root.doshsldr.value) - 1

                    MDTextFieldRect:
                        id: dosh
                        text: "0.00"
                        hint_text: "Enter value"
                        size_hint: 0.2, 0.7
                        pos_hint: {"x":0.70,"center_y":0.5}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)
                        
                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.dosh.text = "{:.2f}".format(float(root.dosh.text) + 1)
                            root.doshsldr.value = float(root.doshsldr.value) + 1


            MDGridLayout:
                cols: 1
                adaptive_height: True
                height: dp(40)

                MDCard:
                    MDIconButton:
                        id: resetdosh
                        size_hint_x: None
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.dosh.text = "{:.2f}".format(0)
                            root.doshsldr.value = 0

                    MDSlider:
                        id: doshsldr
                        min: 0
                        max: 450
                        value: 0
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.dosh.text = "{:.2f}".format(doshsldr.value)
                        
                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.dosh.text = "{:.2f}".format(round(float(root.dosh.text),0))
                            root.doshsldr.value = round(float(root.doshsldr.value),0)

            OneLineIconListItem:
                height: dp(120)
                on_release:
                    root.statepressed = 2
                    app.screen_helper.current = 'thermostate'
                    app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "State 2:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDRaisedButton:
                    text: "2"
                    font_size: "24sp"
                    size_hint: None,0.45
                    pos_hint: {"x":0.05,"center_y":0.45}
                    on_release:
                        root.statepressed = 2
                        app.screen_helper.current = 'thermostate'
                        app.screen_helper.transition.direction = 'left'

      
                MDLabel:
                    text: "Temperature [C]:"
                    theme_text_color: "Custom"
                    size_hint_x : 0.4
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.35,"y":0.10}

                MDLabel:
                    id: t21
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":-0.25}

                MDLabel:
                    id: p21
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            OneLineIconListItem:
                height: dp(120)
                on_release:
                    root.statepressed = 3
                    app.screen_helper.current = 'thermostate'
                    app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "State 3:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDRaisedButton:
                    text: "3"
                    font_size: "24sp"
                    size_hint: 0.15,0.45
                    pos_hint: {"x":0.05,"center_y":0.45}
                    on_release:
                        root.statepressed = 3
                        app.screen_helper.current = 'thermostate'
                        app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "Temperature [C]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":0.10}

                MDLabel:
                    id: t3
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":-0.25}

                MDLabel:
                    id: p3
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            MDToolbar:
                title: "Turbine"
                md_bg_color: (0.60, 0.76, 1, 1)

            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: Window.width*0.316239316
                allow_stretch: True
                keep_ratio: False

                Image:
                    allow_stretch: True
                    keep_ratio: False
                    source:"TurbineIcon.png"

            OneLineIconListItem:
                height: dp(120)
                on_release:
                    root.statepressed = 4
                    app.screen_helper.current = 'thermostate'
                    app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "State 4:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDRaisedButton:
                    text: "4"
                    font_size: "24sp"
                    size_hint: 0.15,0.45
                    pos_hint: {"x":0.05,"center_y":0.45}
                    on_release:
                        root.statepressed = 4
                        app.screen_helper.current = 'thermostate'
                        app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "Temperature [C]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":0.10}

                MDLabel:
                    id: t4
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":-0.25}

                MDLabel:
                    id: p4
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            MDToolbar:
                title: "Heat Sink & Condenser"
                md_bg_color: (0.60, 0.76, 1, 1)

            OneLineIconListItem:
                height: dp(120)
                on_release:
                    root.statepressed = 1
                    app.screen_helper.current = 'thermostate'
                    app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "State 1:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDRaisedButton:
                    text: "1"
                    font_size: "24sp"
                    size_hint: 0.15,0.45
                    pos_hint: {"x":0.05,"center_y":0.45}
                    on_release:
                        root.statepressed = 1
                        app.screen_helper.current = 'thermostate'
                        app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "Temperature [C]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":0.10}

                MDLabel:
                    id: t1
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":-0.25}

                MDLabel:
                    id: p1
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            MDGridLayout:
                cols: 1
                height: dp(25)
                adaptive_height: True

                MDCard:
                
                    MDLabel:
                        text: "   Condenser:"
                        font_style: "Button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        pos_hint: {"x":0.10,"y":0.1}
                        
            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itempinchpoint
                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "information"
                        on_release: root.show_evap_custom_bottom_sheet("pinchpoint")

                    MDLabel:
                        text: "Pinch point [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.35
                        pos_hint: {"x":0.25,"y":0.05}
                        
                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pinchcond.text = "{:.2f}".format(float(root.pinchcond.text) - 1)
                            root.pinchcondsldr.value = float(root.pinchcondsldr.value) - 1

                    MDTextFieldRect:
                        id: pinchcond
                        text: "5.00"
                        hint_text: "Enter value"
                        size_hint: 0.2,0.7
                        pos_hint: {"x":0.70,"y":0.15}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)
                        
                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pinchcond.text = "{:.2f}".format(float(root.pinchcond.text) + 1)
                            root.pinchcondsldr.value = float(root.pinchcondsldr.value) + 1

            MDGridLayout:
                cols: 1
                adaptive_height: True
                height: dp(40)

                MDCard:
                    MDIconButton:
                        id: resetpinchcond
                        size_hint_x: None
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.pinchcond.text = "{:.2f}".format(5)
                            root.pinchcondsldr.value = 5

                    MDSlider:
                        id: pinchcondsldr
                        min: 1
                        max: 30
                        value: 5
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.pinchcond.text = "{:.2f}".format(pinchcondsldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.pinchcond.text = "{:.2f}".format(round(float(root.pinchcond.text),0))
                            root.pinchcondsldr.value = round(float(root.pinchcondsldr.value),0)

            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itempinchpoint
                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "information"
                        on_release: root.show_evap_custom_bottom_sheet("pinchpoint")

                    MDLabel:
                        text: "Degrees of subcooling [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.35
                        pos_hint: {"x":0.25,"y":0.05}
                        
                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.dosc.text = "{:.2f}".format(float(root.dosc.text) - 1)
                            root.doscsldr.value = float(root.doscsldr.value) - 1

                    MDTextFieldRect:
                        id: dosc
                        text: "0.00"
                        hint_text: "Enter value"
                        size_hint: 0.2,0.7
                        pos_hint: {"x":0.70,"y":0.15}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)
                        
                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.dosc.text = "{:.2f}".format(float(root.dosc.text) + 1)
                            root.doscsldr.value = float(root.doscsldr.value) + 1

            MDGridLayout:
                cols: 1
                adaptive_height: True
                height: dp(40)

                MDCard:
                    MDIconButton:
                        id: resetdosc
                        size_hint_x: None
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.dosc.text = "{:.2f}".format(0)
                            root.doscsldr.value = 0

                    MDSlider:
                        id: doscsldr
                        min: 0
                        max: 30
                        value: 0
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.dosc.text = "{:.2f}".format(doscsldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.dosc.text = "{:.2f}".format(round(float(root.dosc.text),0))
                            root.doscsldr.value = round(float(root.doscsldr.value),0)
            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: Window.width*0.427272727
                allow_stretch: True
                keep_ratio: False

                Image:
                    allow_stretch: True
                    keep_ratio: False
                    source:"CondenserIcon.png"

            OneLineIconListItem:
                id: heatsinkbutton
                text: "Heat Sink : Water"
                font_style: "H6"
                theme_text_color: "Custom"
                text_color: (0.28, 0.39, 0.63, 1)
            MDGridLayout:
                cols: 1
                height: dp(25)
                adaptive_height: True

                MDCard:
                    MDLabel:
                        text: "   Cold fluid Inputs:"
                        font_style: "Button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        pos_hint: {"x":0.10,"y":0.0}

            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itemcoldinlettemp

                    MDLabel:
                        text: "   Inlet Temperature [C]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.45
                        pos_hint: {"center_x":0.25,"center_y":0.5}

                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.tw1.text = "{:.2f}".format(float(root.tw1.text) - 5)
                            root.tw1sldr.value = float(root.tw1sldr.value) - 5

                    MDTextFieldRect:
                        id: tw1
                        text: "15.0"
                        hint_text: "Enter value"
                        size_hint: 0.25,0.7
                        pos_hint: {"x":0.65,"center_y":0.5}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)

                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.tw1.text = "{:.2f}".format(float(root.tw1.text) + 5)
                            root.tw1sldr.value = float(root.tw1sldr.value) + 5


            MDGridLayout:
                cols: 1
                height: dp(40)
                adaptive_height: True

                MDCard:

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "restore"
                        on_release:
                            root.tw1.text = "{:.2f}".format(15)
                            root.tw1sldr.value = 15

                    MDSlider:
                        id: tw1sldr
                        min: 1
                        max: 60
                        value: 15
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.tw1.text = "{:.2f}".format(tw1sldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.tw1.text = "{:.2f}".format(round(float(root.tw1.text)))
                            root.tw1sldr.value = round(float(root.tw1sldr.value))

            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itemcoldinletpres

                    MDLabel:
                        text: "   Inlet Pressure [bar]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.45
                        pos_hint: {"x":0.15,"y":0.05}

                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pw1.text = "{:.2f}".format(float(root.pw1.text) - 0.2)
                            root.pw1sldr.value = float(root.pw1sldr.value) - 0.2

                    MDTextFieldRect:
                        id: pw1
                        text: "1.013"
                        hint_text: "Enter value"
                        size_hint: 0.25,0.7
                        pos_hint: {"x":0.70,"y":0.15}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)

                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.pw1.text = "{:.2f}".format(float(root.pw1.text) + 0.2)
                            root.pw1sldr.value = float(root.pw1sldr.value) + 0.2



            MDGridLayout:
                cols: 1
                height: dp(40)
                adaptive_height: True

                MDCard:

                    MDIconButton:
                        theme_text_color: "Custom"
                        size_hint_x : None
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.pw1.text = "{:.3f}".format(1.013)
                            root.pw1sldr.value = 1.013

                    MDSlider:
                        id: pw1sldr
                        min: 0.5
                        max: 3.5
                        value: 1.013
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.pw1.text = "{:.3f}".format(pw1sldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.pw1.text = "{:.2f}".format(round(float(root.pw1.text),1))
                            root.pw1sldr.value = round(float(root.pw1sldr.value),1)

            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:
                    id: itemcoldmflow

                    MDLabel:
                        text: "   Mass Flow [kg/s]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.45
                        pos_hint: {"x":0.15,"y":0.05}

                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.mwflow.text = "{:.2f}".format(float(root.mwflow.text) - 0.5)
                            root.mwflowsldr.value = float(root.mwflowsldr.value) - 0.5

                    MDTextFieldRect:
                        id: mwflow
                        text: "10"
                        hint_text: "Enter value"
                        size_hint: 0.25,0.7
                        pos_hint: {"x":0.70,"y":0.15}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)

                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.mwflow.text = "{:.2f}".format(float(root.mwflow.text) + 0.5)
                            root.mwflowsldr.value = float(root.mwflowsldr.value) + 0.5

            MDGridLayout:
                cols: 1
                height: dp(40)
                adaptive_height: True

                MDCard:
                    MDIconButton:
                        size_hint: None,None
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"
                        on_release:
                            root.mwflow.text = "{:.2f}".format(10)
                            root.mhflowsldr.value = 10

                    MDSlider:
                        id: mwflowsldr
                        min: 1
                        max: 35
                        value: 10
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.mwflow.text = "{:.2f}".format(mwflowsldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.mwflow.text = "{:.2f}".format(round(float(root.mwflow.text),1))
                            root.mwflowsldr.value = round(float(root.mwflowsldr.value),1)

            OneLineIconListItem:
                height: dp(120)
                MDLabel:
                    text: "Cold fluid Outputs:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDLabel:
                    text: "Outlet Temperature [C]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.5
                    pos_hint: {"x":0.15,"y":0.10}

                MDLabel:
                    id: tw2
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.65,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Outlet Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.5
                    pos_hint: {"x":0.15,"y":-0.25}

                MDLabel:
                    id: pw2
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.65,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

            MDToolbar:
                title: "Pump"
                md_bg_color: (0.60, 0.76, 1, 1)

            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: Window.width*0.316239316
                allow_stretch: True
                keep_ratio: False

                Image:
                    allow_stretch: True
                    keep_ratio: False
                    source:"PumpIcon.png"
                    
            MDGridLayout:
                cols: 1
                height: dp(25)
                adaptive_height: True

                MDCard:
                    MDLabel:
                        text: "   Pump Inputs:"
                        font_style: "Button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        pos_hint: {"x":0.10,"y":0.0}

            MDGridLayout:
                cols: 1
                height: dp(45)
                adaptive_height: True

                MDCard:

                    MDLabel:
                        text: "   Isentropic efficiency [-]:"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : 0.45
                        pos_hint: {"center_x":0.25,"center_y":0.5}

                    MDIconButton:
                        icon: "minus"
                        pos_hint: {"x": 0.55, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.npump.text = "{:.2f}".format(float(root.npump.text) - 0.01)
                            root.npumpsldr.value = float(root.npumpsldr.value) - 0.01

                    MDTextFieldRect:
                        id: npump
                        text: "0.90"
                        hint_text: "Enter value"
                        size_hint: 0.25,0.7
                        pos_hint: {"x":0.65,"center_y":0.5}
                        color_mode: 'custom'
                        multiline: False
                        line_color_focus: (0.28, 0.39, 0.63, 1)

                    MDIconButton:
                        icon: "plus"
                        pos_hint: {"x": 0.85, "center_y": .5}
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        on_release:
                            root.npump.text = "{:.2f}".format(float(root.npump.text) + 0.01)
                            root.npumpsldr.value = float(root.npumpsldr.value) + 0.01


            MDGridLayout:
                cols: 1
                height: dp(40)
                adaptive_height: True

                MDCard:

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "restore"
                        on_release:
                            root.npump.text = "{:.2f}".format(0.90)
                            root.npumpsldr.value = 0.9

                    MDSlider:
                        id: npumpsldr
                        min: 0.4
                        max: 1
                        value: 0.90
                        size_hint_x : 0.7
                        pos_hint: {"x":0.10}
                        hint: False
                        thumb_color_down: (0.28, 0.39, 0.63, 1)
                        on_value:
                            root.npump.text = "{:.2f}".format(npumpsldr.value)

                    MDIconButton:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint_x : None
                        pos_hint: {"center_x": 0.5, "center_y": .5}
                        icon: "alpha-r-circle-outline"
                        on_release:
                            root.npump.text = "{:.2f}".format(round(float(root.npump.text), 1))
                            root.npumpsldr.value = round(float(root.npumpsldr.value), 1)

            OneLineIconListItem:
                height: dp(120)
                on_release:
                    root.statepressed = 2
                    app.screen_helper.current = 'thermostate'
                    app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "State 2:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"y":0.4}

                MDRaisedButton:
                    text: "2"
                    font_size: "24sp"
                    size_hint: 0.15,0.45
                    pos_hint: {"x":0.05,"center_y":0.45}
                    on_release:
                        root.statepressed = 2
                        app.screen_helper.current = 'thermostate'
                        app.screen_helper.transition.direction = 'left'

                MDLabel:
                    text: "Temperature [C]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":0.10}

                MDLabel:
                    id: t2
                    text: "None"
                    hint_text: "Enter value"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.475}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

                MDLabel:
                    text: "Pressure [bar]:"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint_x : 0.4
                    pos_hint: {"x":0.35,"y":-0.25}

                MDLabel:
                    id: p2
                    text: "None"
                    size_hint: 0.25,0.25
                    pos_hint: {"x":0.75,"y":0.125}
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)

<Thermotab3>:
    pr:pr
    qin:qin
    wout:wout
    win:win
    wnet:wnet
    nth:nth
    ncarnot:ncarnot
    thermspinner:thermspinner
    orientation: "vertical"
    cols: 1
    id: thermotab3
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        MDGridLayout:
            id: box
            cols: 1
            adaptive_height: True
            
            MDToolbar:
                title: "Calculate & Results"
                md_bg_color: (0.60, 0.76, 1, 1)
                

            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: dp(100)
                allow_stretch: True
                keep_ratio: False

                MDSpinner:
                    id: thermspinner
                    size_hint: None, None
                    size: dp(46), dp(46)
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    determinate_time: "3"
                    active: False

                MDRoundFlatIconButton:
                    text: "Calculate"
                    icon: "calculator"
                    font_size: dp(22)
                    size_hint: None, None
                    size: dp(150), dp(50)
                    pos_hint: {"center_x":0.5,"center_y":0.5}
                    on_release:
                        root.ThermCalculations_thread()

            OneLineIconListItem:
                height: dp(30)
                MDLabel:
                    text: "Results:"
                    font_style: "Button"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: pr
                    text: "Pressure Ratio : None [-]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: qin
                    text: "Heat Duty : None [kW]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: wout
                    text: "Turbine Power Output : None [kW]"
                    size_hint_x: 1
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: win
                    text: "Pump Power Input : None [kW]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: wnet
                    text: "Net Power Output : None [kW]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: nth
                    text: "Thermal Efficiency : None [%]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}

            OneLineIconListItem:
                MDLabel:
                    id: ncarnot
                    text: "Carnot Efficiency : None [%]"
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.9,None
                    pos_hint: {"x":0.10,"center_y":0.5}
                    
            OneLineIconListItem:
                height: dp(70)
                MDFillRoundFlatIconButton:
                    text: "Go to Main Screen"
                    icon: "arrow-right-thick"
                    font_size: dp(17)
                    size_hint: None, None
                    height: dp(50)
                    pos_hint: {"center_x":0.5,"center_y":0.5}
                    theme_text_color: "Custom"
                    md_bg_color:  (0.28, 0.39, 0.63, 1)
                    on_release: 
                        app.root.current = 'main'

<EvaporatorPropCustomSheet@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    height: dp(450)

    MDToolbar:
        title: root.title
        md_bg_color: (0.28, 0.39, 0.63, 1)
        height: dp(60)

    ScrollView:

        MDGridLayout:
            cols: 1
            adaptive_height: True
            
            OneLineIconListItem:
                height: dp(240)
                MDLabel:
                    text: root.text
                    theme_text_color: "Custom"
                    text_color: (0.28, 0.39, 0.63, 1)
                    size_hint: 0.95, None
                    pos_hint: {"x":0.05,"center_y":0.5}
                    
            MDGridLayout:
                cols: 2
                adaptive_height: True
                OneLineIconListItem:
                    height: dp(105)
                    size_hint: 0.15, None
                    IconLeftWidget:
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        icon: "restore"

                OneLineIconListItem:
                    height: dp(105)
                    size_hint: 0.85, None
                    MDLabel:
                        text: "If you want to restore the parameter's value to the calculated value or the default one press the reset button"
                        theme_text_color: "Custom"
                        text_color: (0.28, 0.39, 0.63, 1)
                        size_hint: 0.95, None
                        pos_hint: {"x":0.05,"top":1}
                    
            MDCard:
                orientation: "vertical"
                padding: dp(8)
                size_hint: 1,None
                height: 275*Window.width/350
                allow_stretch: True
                keep_ratio: False

                Image:
                    allow_stretch: True
                    keep_ratio: False
                    source: root.image
                    
<WorkingFluidInfoScreen>
    id: workingfluidinfoscreen
    name: 'workingfluidinfo'

    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: "Information"
                        md_bg_color: (0.28, 0.39, 0.63, 1)
                        left_action_items: [["arrow-left-thick",  lambda x: app.change_screen('thermo')]]
                        elevation:5

                    ScrollView:

                        MDGridLayout:
                            cols: 1
                            adaptive_height: True

                            OneLineIconListItem:
                                height: dp(140)
                                MDLabel:
                                    text: "Select a working fluid for the calculation of the Organic Rankine Cycle thermodynamic parameters, from a list which is provided in the working fluid line. As you selected the working fluid you can define the mass flow of for the cycle simulation."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(150)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "plus"

                                IconRightWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "minus"

                                MDLabel:
                                    text: "Press minus or plus icon to decrease or increase the value of the working fluid's mass flow. You can use also the slider below to adjust the prefarable mass flow."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.55, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(90)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "restore"

                                MDLabel:
                                    text: "Press the reset button if you want to reset working fluid's mass flow to the default value"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.60, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(100)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "alpha-r-circle-outline"

                                MDLabel:
                                    text: "Press the R button if you want to round the mass flow value you have selected through the slider"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.60, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            OneLineIconListItem:
                                height: dp(210)
                                MDLabel:
                                    text: "Once the desired mass flow will be selected, there is no need to select any other parameters, such as pressure or temperatures at each state. ORCestra will calculate the optimal values for the pressure ratio, maximum tempreatures, etc., for the given mass flow, to maximise the net-power output, taking into consideration the heat source and heat sink inputs and the constrains of the components."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height: dp(320)
                                allow_stretch: True
                                keep_ratio: False
                                pos_hint: {"x":0,"top":1}

                                Image:
                                    allow_stretch: True
                                    keep_ratio: False
                                    source:"Power_MassFlow.PNG"

                            OneLineIconListItem:
                                height: dp(100)
                                MDLabel:
                                    text: "ORCestra gives also the opportunity to find the optimal mass flow which maximises the net-power output for the given heat source and heat sink conditions and constrains"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            MDGridLayout:
                                cols: 1
                                height: dp(150)
                                adaptive_height: True

                                MDCard:
                                    MDLabel:
                                        text: " "
                                        size_hint_x : 0.05

                                    MDSwitch:
                                        size_hint_x: 0.15
                                        pos_hint: {"center_x":0.5,"center_y":0.5}

                                    MDLabel:
                                        text: " "
                                        size_hint_x : 0.05

                                    MDLabel:
                                        text: "By clicking on the switch button, working fluid mass flow is no longer an input and it is added to the optimisation process which will calculated the optimal value to maximise the net-power."
                                        theme_text_color: "Custom"
                                        text_color: (0.28, 0.39, 0.63, 1)
                                        size_hint_x : 0.55
                                        pos_hint: {"center_x":0.5,"center_y":0.5}

                                    MDLabel:
                                        text: " "
                                        size_hint_x : 0.05

<HeatSourceInfoScreen>
    id: heatsourceinfoscreen
    name: 'heatsourceinfo'

    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: "Information"
                        md_bg_color: (0.28, 0.39, 0.63, 1)
                        left_action_items: [["arrow-left-thick",  lambda x: app.change_screen('thermo')]]
                        elevation:5

                    ScrollView:

                        MDGridLayout:
                            cols: 1
                            adaptive_height: True

                            OneLineIconListItem:
                                height: dp(160)
                                MDLabel:
                                    text: "Select the necessary heat source and heat sink inputs for the calculation of the Organic Rankine Cycle thermodynamic parameters, while setting the necessary component constrains."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(150)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "plus"

                                IconRightWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "minus"

                                MDLabel:
                                    text: "Press minus or plus icon to decrease or increase the value of each parameter. You can use also the slider below to adjust the prefarable parameter value."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.55, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(90)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "restore"

                                MDLabel:
                                    text: "Press the reset button if you want to reset each parameter's value to the default value"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.60, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(100)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "alpha-r-circle-outline"

                                MDLabel:
                                    text: "Press the R button if you want to round the value you have selected through the slider"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.60, None
                                    pos_hint: {"center_x":0.5,"center_y":0.5}

                            MDList:
                                OneLineIconListItem:
                                    id: heatsourcebutton
                                    text: "Heat Source : Select"
                                    font_style: "H6"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    pos_hint: {"center_x":0.5, "center_y":0.5}

                            OneLineIconListItem:
                                height: dp(200)
                                MDLabel:
                                    text: "You can select and adjust the mass flow rate, the inlet temperature and the inlet pressure of the heat source and the heat sink. The heat source can be selected either Exhaust Gases or Hot Steam, where the user has the opportunity to vary the Exhaust Gas composition. For the Heat Sink ORCestra provides only Cold Water as a working media for now."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(320)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "alarm-panel-outline"

                                MDLabel:
                                    text: "When you press the Exhaust Gases option, a pop-up Window is shown with the composition of the Gas. You can change the values of Exhaust Gases composition, taking into consideration that the sum of of all components molar fraction must be 1. When you change the molar fraction of one component, you can use the calculator button, which will calculate the remaining fraction, to have the molar faction sum at unity."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.65, None
                                    pos_hint: {"center_x":0.6,"center_y":0.5}

                            MDGridLayout:
                                cols: 1
                                height: dp(25)
                                adaptive_height: True

                                MDCard:
                                
                                    MDLabel:
                                        text: "   Evaporator:"
                                        font_style: "Button"
                                        theme_text_color: "Custom"
                                        text_color: (0.28, 0.39, 0.63, 1)
                                        pos_hint: {"x":0.10,"y":0.1}

                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height: dp(290)
                                allow_stretch: True
                                keep_ratio: False
                                pos_hint: {"x":0,"top":1}

                                Image:
                                    allow_stretch: True
                                    keep_ratio: False
                                    source:"ThermPinchPoint.JPG"

                            OneLineIconListItem:
                                height: dp(180)
                                MDLabel:
                                    text: "You can set the main constrains of the evaporator component which are the evaporator pinch point and the degrees of superheating. The pinch point is the minimum temperature difference between the hot side and the cold side of the heat exchanger. "
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(350)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "alert"

                                MDLabel:
                                    text: "The calculation of the Organic Rankine parameters is based on the subcritical cycle, meaning that all the estimated parameters are calculated below the critical point. For now ORCestra does not support transcritical cycle. If the inlet temperature of the heat source is too high, the optimisation process may lead to values above critical point. For this reason, ORCestra will change the value of the pinch point in order to ensure that the resulting thermodynamic cycle will remain subcritical."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.7, None
                                    pos_hint: {"center_x":0.6,"center_y":0.5}

                            MDCard:
                                orientation: "vertical"
                                padding: dp(8)
                                size_hint: 1,None
                                height: dp(290)
                                allow_stretch: True
                                keep_ratio: False
                                pos_hint: {"x":0,"top":1}

                                Image:
                                    allow_stretch: True
                                    keep_ratio: False
                                    source:"ThermDosh.JPG"

                            OneLineIconListItem:
                                height: dp(170)
                                MDLabel:
                                    text: "You can set also the degrees of superheating (DoSH). Degrees of superheating are expressed as the temperature difference between the turbine inlet temperature (T3) and the saturation temperature for the given pressure (P3), as it is shown in the figure"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

                            OneLineAvatarIconListItem:
                                height: dp(400)

                                IconLeftWidget:
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    icon: "alert"

                                MDLabel:
                                    text: "Another constrain which is set during the optimisation of the Organic Rankine Cycle is that the expansion process is obliged to be in the gas phase completely, mainly for manufacturing reasons. These reasons are primearily to avoid droplets in the turbine blades which may lead to blade erosion. In the case of Wet fluids especially if the Degrees of superheating are equal to zero (0) the turbine exit will be in liquid-gas mixture region and not in the gas phase. For this reason ORCestra will re-estimate the value of Degrees of superheating in order to ensure that the expansion process will be performed in the gas phase."
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.7, None
                                    pos_hint: {"center_x":0.6,"center_y":0.5}

                            OneLineIconListItem:
                                height: dp(90)
                                MDLabel:
                                    text: "Similarly, we can set the necessary constrains in the Condenser by setting the pinch point of the condenser and the degress of subcooling "
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.90, None
                                    pos_hint: {"center_x":0.55,"center_y":0.5}

<ThermoStateScreen>
    statebar:statebar
    rho:rho
    vspec:vspec
    enth:enth
    entr:entr
    soundspeed:soundspeed
    comprfactor:comprfactor
    fundder:fundder
    cp:cp
    cv:cv
    temp:temp
    pres:pres
    
    id: thermostatescreen
    name: 'thermostate'
    
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        id: statebar
                        title: 'State 2'
                        left_action_items: [["arrow-left-thick",  lambda x: app.change_screen('thermo')]]
                        elevation:5

                    ScrollView:
                        MDGridLayout:
                            id: box
                            cols: 1
                            adaptive_height: True
                            
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: temp
                                    text: "Temperature : None [C]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: pres
                                    text: "Pressure : None [bar]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                            
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: rho
                                    text: "Density : None [kg/m3]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: vspec
                                    text: "Specific Volume : None [m3/kg]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: enth
                                    text: "Enthalpy : None [kJ/kg]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: entr
                                    text: "Entropy : None [kJ/kg-K]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}

                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: soundspeed
                                    text: "Speed of sound : None [m/s]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: comprfactor
                                    text: "Compressibility Factor : None [-]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: fundder
                                    text: "Foundamental Derivative : None [-]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
                                    
                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: cp
                                    text: "Specific Heat Capacity Cp : None [kJ/kg-K]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}

                            OneLineIconListItem:
                                height: dp(60)

                                MDLabel:
                                    id: cv
                                    text: "Specific Heat Capacity Cv : None [kJ/kg-K]"
                                    theme_text_color: "Custom"
                                    text_color: (0.28, 0.39, 0.63, 1)
                                    size_hint: 0.9, None
                                    pos_hint: {"x":0.10,"center_y":0.5}
